### ISSUE TITLE
item_properties_part1.csv & item_properties_part2.csv missing

### ISSUE THREAD

**Issue by zangt2** [nick-carroll1/SA2C-Recommender-System#1]
Dear nick @nick-carroll1, I am attempting to study your code and I run into an issue with item_properties_part1.csv & item_properties_part2.csv. Would you please include them if convenient? Thank you so much for your patience reading through my request.

**Comment by nick-carroll1** [comment]
The data was too large to be hosted on GitHub.  Attached are heads of each of the csv files to get an idea what the data looked like for this project.
[item_properties.csv](https://github.com/nick-carroll1/SA2C-Recommender-System/files/15068263/item_properties.csv)
[item_properties2.csv](https://github.com/nick-carroll1/SA2C-Recommender-System/files/15068264/item_properties2.csv)
